### ISSUE TITLE
Change IPMX Controller to IPMX Device Controller

### ISSUE THREAD

**Issue by rbgodwin** [AMWA-TV/nmos-edid-connection-management#14]
Capturing some discussions from the EDID Slack channel for input from Gareth in this issue  to track further discussions and changes to the Arch document. 

Gareth S-B (Sony)  2:50 PM
I know there has been some to-and-fro about the naming. I do find IPMX Controller a little confusing myself. We tend to use NMOS Client, Control System and Controller as close synonyms in specs and other material at the moment. If I understand correctly, the proposed IPMX Controller is something with an API living alongside/within a Device. Would 'IPMX Device Control' (or perhaps 'IPMX Device Controller') work as a name, more clearly distinct from IPMX Control System? (edited) 

Randy Godwin  11:08 AM

I like IPMX Device Controller. It would resolve some of the confusion associated with the user-stories that involve control of IS-05 connections. It also would fit for some of the "out-of-scope but considered" User-Stories we have in the Google Doc but not included in the architecture document.  CEC, HDCP, etc would all likely be associated with an IPMX Device Controller. Likely in an implementation though the IPMX Device Controller would also be responsible for doing logic such as parsing out a monitor's EDID and populating receiver caps according to a Phase II Best Practices,etc. All those things seem to fit with a name IPMX Device Controller.

Gareth S-B (Sony)  11:13 AM
Calling the entity an IPMX Device Controller sounds good to me - it's a doer - as distinct from an API defined for that entity, which might be the IPMX Device Control (no -er) API? (if nothing pithier comes to mind!)

**Comment by N-Nagorny** [comment]
Hi @rbgodwin.

I aligned terminology in pull request #23. I propose to add it to the agenda for the next call.
