### ISSUE TITLE
Relationship between Receivers and Destination

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-edid-connection-management#18]
Just looking at the tentative RAML on the [tentative-raml branch](https://github.com/AMWA-TV/nmos-edid-connection-management/tree/tentative-raml)...

I assume a Destination, like an IS-04 Source, is for a specific format?
So I assume there are audio Receivers and Destinations as well as video ones?

I assume there's a 1:1 relationship between a Receiver and a Destination?
Or can there be more than one Receiver associated with a Destination?

How are the video/audio Receivers/Destinations tied together, using BCP-002-01 "natural grouping"? 

Current tentative API has:

* **/receivers**
  * **/{receiverId}**
    * **/destination**

If the relationship isn't 1:1 between Receivers and Destinations, and possibly even if it is, would this be better?

* **/receivers**
  * **/{receiverId}**
    * **/destinationid**
* **/destinations**
  * **/{destinationId}**

**Comment by prince-chrismc** [comment]
> If the relationship isn't 1:1 between Receivers and Destinations, and possibly even if it is, would this be better?

On one of out last calls Andy pointed this out, and your suggestion matches the consensus of the group. My impression/hope was the second phase would allow the group to revise that content 🙏

UPDATE: The tentative branch was merged. The section in question is https://github.com/AMWA-TV/nmos-edid-connection-management/blob/6064e48fa25a97a36c9ab40c001b5ddf5b02310b/APIs/IPMXAPI.raml#L47-L69

**Comment by N-Nagorny** [comment]
The original idea behind Destination was representing a physical (HDMI in particular) sink which a logical Receiver is associated with. As I remember, we didn't finally agree on Destination purpose but if it will stay the same, then one Destination may have multiple Receivers (e.g. video Receiver and audio Receiver associated with a single TV). Also, I see that one Receiver can be associated with multiple Destinations (e.g. single multicast group listener sends video to multiple physical displays).
So looks like revising Destination role is a thing we should do during Phase II.

**Comment by garethsb** [comment]
I am not sure about that... I expect that Destination would be the counterpart of Source, and therefore single `format`, etc. Flows are  representations of the same Source with different technical attributes (`grain_rate`, `frame_width`, `frame_height`, etc.), and a Sender transmits the stream for a Flow on a particular `transport` and `interfaces`. A number of Sources may be associated (audio/video/data), and likewise a number of Destinations. In the same way, I expect there may be multiple Receivers for a Destination, but only to represent different transports/interfaces for getting the stream into the Destination.
