### ISSUE TITLE
Format for Best Practices on Mapping from EDID to NMOS Resources

### ISSUE THREAD

**Issue by rbgodwin** [AMWA-TV/nmos-edid-connection-management#28]
This issue is to track decision on initial format of the Best Practices document deliverable for our activity.

The document needs to include specifications for going from an EDID of a IPMX type device (usually an HDMI Monitor) with EDID to the following NMOS Resources

1) IS-04 Extended Receiver Caps
2) Newly Developed IS-EDID-CM and IPMX Device Controller Resource
3) IS-04 Sources/Senders (if applicable).

**Comment by prince-chrismc** [comment]
Exacting the content from our spreadsheet so it's easier to comment on

### Mapping of EDID to Rx-Caps

EDID block | EDID parameter | Receiver Caps URN | Spec | Version | Parameter Location | Parameter Name | Parameter Type | Notes
-- | -- | -- | -- | -- | -- | -- | -- | --
Supported features (byte 24) | Display type (digital) | urn:x-nmos:cap:format: color_sampling | IS-04 | v1.1 | flow_video_raw | components | array of object (with name - string (enum), width, height, bit_depth - all integers) | Can be also described with ST 2110-20:2017 paragraph 7.4.1 "sampling" SDP fmtp. Has 4 values:00 = RGB 4:4:401 = RGB 4:4:4 + YCrCb 4:4:410 = RGB 4:4:4 + YCrCb 4:2:211 = RGB 4:4:4 + YCrCb 4:4:4 + YCrCb 4:2:2
Established timings and Standard Timings | H resolution | urn:x-nmos:cap:format: frame_width | IS-04 | v1.1 | flow_video | frame_width | integer | Established Timings is a static set of 17 modes consisting of H res, V res and frame rate.
Established timings and Standard Timings | V resolution | urn:x-nmos:cap:format: frame_height | IS-04 | v1.1 | flow_video | frame_height | integer | Established Timings is a static set of 17 modes consisting of H res, V res and frame rate.
Established timings and Standard Timings | Frame rate | urn:x-nmos:cap:format: grain_rate | IS-04 | v1.1 | flow_core | grain_rate | object (numerator and denominator) | Established Timings is a static set of 17 modes consisting of H res, V res and frame rate.
EIA/CEA-861 extension/Short Audio Descriptor | Audio Format | urn:x-nmos:cap: format:media_type | IS-04 | v1.1 | flow_<all> | media_type | string |  
EIA/CEA-861 extension/Short Audio Descriptor | Number of channels | urn:x-nmos:cap: format:channel_count | IS-04 | v1.1 | source_audio | channels | array of object (with label - string and symbol - string (enum)) |  
EIA/CEA-861 extension/Short Audio Descriptor | Sampling rate | urn:x-nmos:cap:format: sample_rate | IS-04 | v1.1 | flow_audio | sample_rate | object (numerator and denominator) |  
EIA/CEA-861 extension/Short Audio Descriptor | Bit depth | urn:x-nmos:cap:format: bit_depth | IS-04 | v1.1 | flow_audio_raw | bit_depth | integer |  
EIA/CEA-861 extension/Speaker Allocation Data Block |   |   | IS-04 | v1.1 | source_audio | channels | array of object (with label - string and symbol - string (enum)) |  
EIA/CEA-861 extension/Vendor Specific Data Block | Deep color modes |   | IS-04 | v1.1 | flow_video_raw | components | array of object (with name - string (enum), width, height, bit_depth - all integers) |  
  | Interlace mode | urn:x-nmos:cap:format: interlace_mode | IS-04 | v1.1 | flow_video | interlace_mode | string (enum) |

**Comment by rbgodwin** [comment]
Thanks @prince-chrismc  I'm thinking along the lines of adding in the schemas from the APIs to the document with recommendations on how to populate based on the EDID elements from the spreadsheet above using the SHOULD, MUST, MAY type language.  What do you think?
