### ISSUE TITLE
Mapping color information

### ISSUE THREAD

**Issue by prince-chrismc** [AMWA-TV/nmos-edid-connection-management#44]
Another import detail which is often used in system calibration is color space, colerimetry, etc.

In Base EDID and extensions blocked we can find various parts of these in CTA-861-G with

- Color Bit Depth: EDID section 3.6.1Video Input Definition Table 3.11 
- Colorimetry DataBlock: CEA section 7.5.5 
- Vendor specific: CEA 7.5.7 Vendor-Specific Video Data Block
   - CEA 5.4 Color Coding & Quantization
   - CEA 5.3 Transfer Characteristic

**Comment by N-Nagorny** [comment]
I added a section about Color Bit Depth and Vendor-Specific Data Block in #67.
Section 5 is recommendations about signal rather than metadata format description.
Section 7.5.5 can't be mapped into https://specs.amwa.tv/nmos-parameter-registers/branches/main/flow-attributes/#colorspace right now.
