### ISSUE TITLE
Behaviour document needs to mention where the EDID API will be exposed

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-edid-connection-management#46]
Traditionally further NMOS APIs are exposed in the IS-04 controls array with a namespace and "href".
We should update the Behaviour document to add this.

Namespace could be:
{
    "type": "urn:x-nmos:control:edid-cm/v1.0",
    "href": "http://hostname/x-nmos/edid-cm/v1.0/"
}

**Comment by N-Nagorny** [comment]
During the meeting today we agreed to `urn:x-nmos:control:sink-mp/v1.0` type.

**Comment by N-Nagorny** [comment]
That's reflected in IS-11, so closing this.
