### ISSUE TITLE
Request from Steering for diagram showing relationship between IS-04 Receiver(s) and Sinks

### ISSUE THREAD

**Issue by rbgodwin** [AMWA-TV/nmos-edid-connection-management#47]
For upcoming Steering review of the deliverable items there was  a suggestion that a diagram that shows the relationship between IS-04 receivers and the new Sink resource would clarify this part of the work.

Suggestion was that something similar to diagrams in info-001 would be  sufficient:
https://e6cfd1ba-033d-44fd-8f16-0027ec40a7b2.filesusr.com/ugd/f66d69_f01cba51bb394872993c2753a39df703.pdf

The 1:1 relationship seems clear but if there is a short use-case or User-Story for others it could also be useful.

**Comment by N-Nagorny** [comment]
Closed because it is extremely obsolete.
