### ISSUE TITLE
Check Audio Format Code in EDID

### ISSUE THREAD

**Issue by N-Nagorny** [AMWA-TV/nmos-edid-connection-management#58]
`media_type` for audio stays in IS-11 because it may be expressed in EDID-driven Receiver Caps. It's needed to investigate if it makes sense to keep `media_type` here.

**Comment by prince-chrismc** [comment]
In IS-11 we have the ability to pass `"bit_depth"` and `"sample_rate"` within the media profiles, should we include EDID settings related to this.

Questions to answer

- Missing mapping
- Importance (required in IS-11)

**Comment by prince-chrismc** [comment]
This is also true for Video's `"component_depth"`

**Comment by N-Nagorny** [comment]
Section 7.5.2 of CTA-861-G shows how sampling frequencies can be extracted for any audio format, so `sample_rate` is covered. I would only add language about making a new Constraint Set for each `sample_rate` found. Regarding Media Profile Schema, I would keep it optional since there are no known frequencies for Basic Audio.

`bit_depth` can be determined only for Linear PCM as I understand. As far as it's shown in `media_type`, I think, it is duplication and `bit_depth` can be deleted from `media_profile_audio.json`.

`component_depth` may be taken from `Video Input Definition` (section 3.6.1) of E-EDID A2 if defined for each video Constraint Set.

**Comment by N-Nagorny** [comment]
Resolved.
