### ISSUE TITLE
Rendering of <details> needs work...

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-edid-connection-management#62]
![Screenshot_20220131-094147_Chrome](https://user-images.githubusercontent.com/31761158/151771123-3caf51e7-0acc-413a-abc6-0e8e7f5690a5.jpg)

**Comment by N-Nagorny** [comment]
I would extract it to `Examples.md` and don't use spoilers at all.

**Comment by N-Nagorny** [comment]
https://github.com/AMWA-TV/bcp-005-01/pull/68 is merged. Closed.
