### ISSUE TITLE
meta:preference value

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-edid-connection-management#64]
> Preferred Vertical Rate united with the frame width and height makes a Constraint Set and SHOULD have a `urn:x-nmos:cap:meta:preference` value [of] `50`

Why recommend fifty? BCP-004-01 allows values between -100 and 100, vs. a default of 0, so that an implementation has a concise way to indicate a preference _for or against_ a small proportion of its Constraint Sets.

**Comment by N-Nagorny** [comment]
Preferred Vertical Rate should become `grain_rate`.

**Comment by garethsb** [comment]
And then I guess it should say something like: The _Preferred Vertical Rate_ SHOULD be indicated by using a higher `urn:x-nmos:cap:meta:preference` value in constraint set(s) describing this value vs. other _Supported Vertical Rates_.
